web_services_homepage:
    path:     /
    defaults: { _controller: WebServicesBundle:Default:index }
################# ROUTING DE Sl-Wassim PLEASE DON'T TOUCH #####################
web_services_affichage_outils:
    path:     /affichageOutilsWS
    defaults: { _controller: WebServicesBundle:Outils:afficherWS }
web_services_detail_outil:
    path:     /detailOutilWS
    defaults: { _controller: WebServicesBundle:Outils:detailWS }
web_services_louer:
    path:     /louerWS
    defaults: { _controller: WebServicesBundle:Outils:louerWS }
web_services_outilDisponibleWS:
    path:     /outilDisponibleWS
    defaults: { _controller: WebServicesBundle:Outils:outilDisponibleWS }
web_services_rechercheOutilWS:
    path:     /rechercheOutilWS
    defaults: { _controller: WebServicesBundle:Outils:rechercheOutilWS }
############################ END ROUNTING DE Sl-Wassim ##########################
########## ROUTING DE MUSTAPHA ###############
web_services_getUserReclame:
    path:     /getusersreclameWS/{idUser}
    defaults: { _controller: WebServicesBundle:ReclamationWS:getUserReclame }
web_services_getServiceRealise:
    path:     /getservicerealiseWS/{idUser}/{idUserDemandeur}
    defaults: { _controller: WebServicesBundle:ReclamationWS:getServiceRealise }
web_services_getDateRealise:
    path:     /getservicerealiseWS/{idUserOffreur}/{idUserDemandeur}/{idService}
    defaults: { _controller: WebServicesBundle:ReclamationWS:getDateRealisation }
web_services_ajouterReclamation:
    path : /ajouterReclamationWS/
    defaults: { _controller: WebServicesBundle:ReclamationWS:AjouterReclamation }
web_services_afficherReclamations:
    path: /afficherReclamationsWS/{idUser}
    defaults: { _controller: WebServicesBundle:ReclamationWS:afficherReclamations }
web_services_getAvisUser:
    path: /getAvisWS/{idUser}
    defaults: { _controller: WebServicesBundle:Avis:getAvisUser}
web_services_modifierAvis:
    path: /modifierAvisWS/
    defaults: { _controller: WebServicesBundle:Avis:modifierAvis }
web_services_ajouterAvis:
    path: /ajouterAvisWS/
    defaults: { _controller: WebServicesBundle:Avis:ajouterAvis }
########## END ROUTING DE MUSTAPHA ###########
########## ROUTING DE Ali ###############
web_services_getAllProduits:
    path:     /getAllProduitsWS
    defaults: { _controller: WebServicesBundle:Produits:afficherWS }
web_services_getAllMesProduits:
    path:     /getAllMesroduitsWS/{id}
    defaults: { _controller: WebServicesBundle:Produits:MesProduitsWS }
web_services_getAllMCategorue:
    path:     /getAllCateorieWS
    defaults: { _controller: WebServicesBundle:Produits:GetAllCategorieWS }
web_services_ModifierProduit:
    path:     /ModifierProduitWS/
    defaults: { _controller: WebServicesBundle:Produits:modifierProduitWS }
web_services_AcheterProduit:
    path:     /AcheterProduitWS/{pro}/{us}/{quantite}
    defaults: { _controller: WebServicesBundle:Produits:acheterWS }
########## END ROUTING DE Ali ###########
########## ROUTING DE YASSINE ###############
web_services_getUser:
    path:       /getUserWs/
    defaults: { _controller: WebServicesBundle:User:getUser }
web_services_getUsers:
    path:       /getUsersWs/
    defaults: { _controller: WebServicesBundle:User:getUsers }
web_services_getUserById:
    path:       /getUserByIdWs/
    defaults: { _controller: WebServicesBundle:User:getUserById }
web_services_getUserByEmail:
    path:       /getUserByEmailWs/
    defaults: { _controller: WebServicesBundle:User:getUserByEmail }
web_services_getUserByUsername:
    path:       /getUserByUsernameWs/
    defaults: { _controller: WebServicesBundle:User:getUserByUsername }
web_services_modifierUser:
    path:       /modifierUserWs/
    defaults: { _controller: WebServicesBundle:User:modifierUser }
web_services_inscriptionUser:
    path:       /inscriptionUserWs/
    defaults: { _controller: WebServicesBundle:User:inscriptionUser }
web_services_modifierSoldeUser:
    path:       /modifierSoldeUserWs/
    defaults: { _controller: WebServicesBundle:User:modifierSoldeUser }
########## END ROUTING DE YASSINE ###########

########## ROUTING DE SLIM ###############
web_services_affichageService:
    path:       /affichageServiceWS/
    defaults: { _controller: WebServicesBundle:Service:afficherWS }
web_services_affichageServiceUser:
    path:       /affichageServiceUserWS/{idUser}
    defaults: { _controller: WebServicesBundle:Service:afficherMesServicesWS }
web_services_getImageServiceUser:
  path:       /getImageServiceUserWS/{idService}
  defaults: { _controller: WebServicesBundle:Service:getImageServiceWS }
web_services_getAllCategorie:
  path:       /getAllCategorieWS/
  defaults: { _controller: WebServicesBundle:Service:getAllCategorieWS }
web_service_getServiceCategorie:
  path:     /getServiceCategorieWS/{idc}
  defaults: {_controller:WebServicesBundle:Service:getServiceCategorieWS}
web_service_ajouterService:
  path:     /ajouterServiceWS
  defaults: {_controller:WebServicesBundle:Service:ajouterServiceWS}
web_service_ajouterProposition:
  path:     /ajouterPropositionWS
  defaults: {_controller:WebServicesBundle:Service:ajouterPropositionWS}
web_service_supprimerServiceUser:
  path:     /supprimerServiceUserWS
  defaults: {_controller:WebServicesBundle:Service:supprimerServiceUserWS}
########## END ROUTING DE SLIM ###########